// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"go-labs-game-platform/internal/repository/postgres"
	"go-labs-game-platform/internal/services/auth"
	"go-labs-game-platform/internal/services/redis"
	"go-labs-game-platform/internal/services/room"
	"go-labs-game-platform/internal/services/user"
)

// Injectors from wire.go:

func Up() (*Dependencies, error) {
	redisRedis, err := redis.New()
	if err != nil {
		return nil, err
	}
	repo, err := postgres.New()
	if err != nil {
		return nil, err
	}
	impl := auth.New(repo)
	userImpl := user.New(repo)
	roomImpl := room.New(repo, redisRedis)
	dependencies := NewDependencies(redisRedis, impl, userImpl, roomImpl)
	return dependencies, nil
}
