// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"go-labs-game-platform/internal/repository/postgres"
	"go-labs-game-platform/internal/services/auth"
	"go-labs-game-platform/internal/services/cache"
	"go-labs-game-platform/internal/services/room"
	"go-labs-game-platform/internal/services/user"
)

// Injectors from wire.go:

func Up() (*Dependencies, error) {
	impl, err := cache.New()
	if err != nil {
		return nil, err
	}
	repo, err := postgres.New()
	if err != nil {
		return nil, err
	}
	authImpl := auth.New(repo)
	userImpl := user.New(repo)
	roomImpl := room.New(impl)
	dependencies := NewDependencies(impl, authImpl, userImpl, roomImpl)
	return dependencies, nil
}
